import type { Meta, StoryObj } from "@storybook/web-components-vite";
import "./button.js";
type ButtonProps = {
    variant: "brand" | "neutral" | "success" | "warning" | "danger";
    appearance: "accent" | "filled" | "outlined" | "plain";
    size: "small" | "medium" | "large";
    pill: boolean;
    href: string;
    target: "_blank" | "_parent" | "_self" | "_top";
    download: string;
    children: string;
};
declare const meta: Meta<ButtonProps>;
export default meta;
type Story = StoryObj<ButtonProps>;
export declare const Primary: Story;
export declare const Default: () => import("lit-html").TemplateResult<1>;
export declare const Variants: () => import("lit-html").TemplateResult<1>;
export declare const Appearances: () => import("lit-html").TemplateResult<1>;
export declare const Sizes: () => import("lit-html").TemplateResult<1>;
export declare const Pill: () => import("lit-html").TemplateResult<1>;
export declare const LinkButtons: () => import("lit-html").TemplateResult<1>;
export declare const IconButtons: () => import("lit-html").TemplateResult<1>;
export declare const CustomWidth: () => import("lit-html").TemplateResult<1>;
export declare const StartEndDecorations: () => import("lit-html").TemplateResult<1>;
export declare const Caret: () => import("lit-html").TemplateResult<1>;
export declare const Loading: () => import("lit-html").TemplateResult<1>;
export declare const Disabled: () => import("lit-html").TemplateResult<1>;
export declare const StylingButtons: () => import("lit-html").TemplateResult<1>;
